export const TOGGLE_COLOR = 'TOGGLE_COLOR';
export const EXAMPLE_REQUEST_START = 'EXAMPLE_REQUEST_START';
export const EXAMPLE_REQUEST_DATA = 'EXAMPLE_REQUEST_DATA';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';